name: pr-check-failure
on:
  workflow_run:
    workflows:
      - pr-check
    types: [ completed ]

jobs:
  comment-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: quipper/comment-failure-action@v0.1.1
